[package]
name = "continous_integration_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "dispatcher"
path = "src/bin/dispatcher.rs"

[[bin]]
name = "repo_observer"
path = "src/bin/repo_observer.rs"

[[bin]]
name = "test_runner"
path = "src/bin/test_runner.rs"
